export const SELECT_CLIENT = 'SELECT_CLIENT'
export const SELECT_PRODUCT = 'SELECT_PRODUCT'
export const QUANTITY_OF_PRODUCTS = 'QUANTITY_OF_PRODUCTS'
export const UPDATE_THE_TOTAL = 'UPDATE_THE_TOTAL'
